### PR TITLE
initializing Farsi(Persian) language

### PR DESCRIPTION
**Pull request by DanielBlackBeard**

### CODE REVIEW

**Comment by DanielBlackBeard** [comment]
Q:I want use action section but it cant run , can you guide me to run it for testing translation ?
thanks

**Comment by zzzgydi** [comment]
You can run and test directly on your computer according to the [development steps](https://github.com/zzzgydi/clash-verge#development). If you want to build it using action on your forked repo, you can remove this line of code in the `.github/workflows/alpha.yml`. And then trigger it manually.

```
  if: startsWith(github.repository, 'zzzgydi')
```

**Comment by DanielBlackBeard** [comment]
Finished 3 bundles at:
        /home/runner/work/clash-verge/clash-verge/src-tauri/target/release/bundle/deb/clash-verge_1.2.3_amd64.deb
        /home/runner/work/clash-verge/clash-verge/src-tauri/target/release/bundle/appimage/clash-verge_1.2.3_amd64.AppImage
        /home/runner/work/clash-verge/clash-verge/src-tauri/target/release/bundle/appimage/clash-verge_1.2.3_amd64.AppImage.tar.gz (updater)

       Error incorrect updater private key password: Missing comment in secret key
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command failed with exit code 1: yarn tauri build -f default-meta

**Comment by zzzgydi** [comment]
Oh, you should remove the pubkey in the tauri.conf.json file. And all of these changed should not pull to this repo.

**Pull request closed without merging**
